name: 'check_blade_templates_php'
description: 'github action template for check old use of php in blade files'
author: 'Anton Koshel <fxpw@outlook.com>'
runs:
  using: 'docker'
  image: 'Dockerfile'
branding:
  icon: 'eye'  
  color: 'gray-dark'